name: Build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build:html && npm run build:pdf
      - name: 'Create distributable'
        run: mkdir public && mv resume.html public/index.html && mv resume.pdf public/
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: pages
          build_dir: public
          fqdn: resume.steve.hair
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
